language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
after_success:
- npm run deploy
env:
  global:
  - secure: "l5RZw0uBzC3Cph039CWTZW5bkjgJHdwH5aQZbCVkADilJ2R7aGF7FFQFgdQi+WB+HadP5VoV38QdbPSPoWmI7+mJ0wKzwylPB4c8i/Z1utLTYTiIhgE1XxCZCpMAAPCVaC8k4D7PhrJcevKK2o+BxxvmInxGjOixGNamsoW1WiEjNUX0Zi2phSJpLeX/43IQD453206SBP8glF/myFBmr+/xNUHiHI2rvQqHojH73CGJR0DexY7uA/E1W2i+4AWEJ/MWejIiAOjuk+6Ove2LMbmicZzsTpVV7DXYDWlE+NiMlnrbRBHhBl3rzfzh/ubxYhiZxrQqmMCfTuQgvqV+HpqBEU+4EJU7n3KPEiCmnKfFN7bEPl9XCFWsPK8yxwAlNbQGnYoWG3sg5NADvQevzSYKN/2IB7byLkzctbTOYqydImPb3VUXU0WIy4Cp1xrSbpcu+YZI/yBvj/Z3dn9Z/GE7iBOOoUHru5D9pbWzFGPHUjzhSbPnlNzNSuoIkOaIn+boSCEDcBJRLFL8AbdJH0H9AVb1/XThQ5HDtXqdWBTYK6MDtDQfLRHc3dtBAdinq7XBEthAOJpL5F6KGUypjotB9AfsB5CubJRaPnD7TH2UGywUQYo6sSh5zmXrXqkSvxYGjLuz0Ra5aybzFW+2LB2or50ZTZEObKmXJa8LU80="
