language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
after_success:
- npm run deploy
env:
  global:
  - secure: "ND5H4EWZ869IsEK45k2XE6YxHtBxjLtjhksjhcmix90a3z7U0r14/GU+/H5nLGHm9mU0OYS6lBYy6hEN3kHyTNOSTAc35r0LgDD5cj62PBNrx86XtR1T8XdERzwyWi3qNEgSERs6/qZJ2crhfXAmnrN1ggL2PXnPu4GYy5jBcSSSrWordkLbk6HMz7H82VUjMt0JrcfWUQKBHcaaB4MLK8XEvNFi6QCJHA5kmZL7aCMrMI7B4RikW7YMn7DZRPX9fisApMY3Nvw9Aox1qQIVs0d/hzI5FJ/XixnGaA28EzokNiBLYk7E9f6mmOe4DUGmZAYSMT14ZjL+K/D9NpnqATSkjXG1eqjr9utObWv/0fKPYqv/F5SeihZhZRlHC/qUTX+3RU0+Zotufs439Xt18WGPQZfVGSXMD2bzvlvxW+R21mC8xKoaaIruJLrdQ+XvZxbPry+wqCmqJcJszUiFUYiS2Qgh6L4TbsU32qcfnMef6i2uOAgV2OhkFrnL2DMsggRDPWkK8PpsZ/TmnOce8xJCKlv6h0JWDyApIyd6OIYpKJe2LEU2vRSoinvzp33DAzetwjhwLCCHOaaqTMQCHjA9pBq5rlDvJo/NAMJ8ZkBxn/sSIxCBD7yRWvF63oEhLPFp1VPJph9ehy/ZzrW+4/lMuSLrmW3XlIh4PDgqL3k="
